[package]
name = "integer_list_bench_test"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
plotters = "0.3.5"

[[bench]]
name = "my_benchmark"
harness = false